export const NEW_GAME = 'NEW_GAME';
export const TOGGLE_FLAG = 'TOGGLE_FLAG';
export const REVEAL_CELL = 'REVEAL_CELL';
export const SET_REVEAL_CELL_STATUS = 'SET_REVEAL_CELL_STATUS';
export const UPDATE_INPUT_MODE = 'UPDATE_INPUT_MODE';
